name: Update Sheet Data

on:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC every day
  workflow_dispatch: # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Run update script
        env:
          GOOGLE_SHEETS_API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
          POCKETHOST_URL: ${{ secrets.POCKETHOST_URL }}
          POCKETHOST_EMAIL: ${{ secrets.POCKETHOST_EMAIL }}
          POCKETHOST_PASSWORD: ${{ secrets.POCKETHOST_PASSWORD }}
        run: |
          node -e "console.log('Node.js version:', process.version)"
          node -e "console.log('NPM version:', require('child_process').execSync('npm -v').toString().trim())"
          node -e "console.log('Current working directory:', process.cwd())"
          node -e "console.log('Directory contents:', require('fs').readdirSync('.'))"
          node -e "console.log('package.json contents:', require('fs').readFileSync('package.json', 'utf8'))"
          node updateSheetData.js
        continue-on-error: true
      - name: Check for errors
        if: failure()
        run: |
          if [ -f npm-debug.log ]; then
            echo "NPM Debug Log:"
            cat npm-debug.log
          fi
          echo "Last 100 lines of updateSheetData.js output:"
          tail -n 100 $GITHUB_WORKSPACE/updateSheetData.log
